name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Generate keystore
      run: |
        keytool -genkeypair -v \
          -keystore gestionpro.keystore \
          -alias gestionpro \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass gestionpro2026 \
          -keypass gestionpro2026 \
          -dname "CN=DAS PRO STUDIO, OU=Mobile, O=DAS PRO STUDIO, L=Niamey, ST=Niamey, C=NE"
        echo "Keystore créé avec succès"
        ls -la gestionpro.keystore
    
    - name: Upload keystore
      uses: actions/upload-artifact@v4
      with:
        name: keystore
        path: gestionpro.keystore
